# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 847bfc72c5a0b5c33a602b119d56ef013de92ceee525705048f33453c4531e2760b87ade2e4d5594b4746fbb8b67e761433676cb0e971c59fa051da8da9d05db

test:
  secret_key_base: 34f04a2af1a3f9489b3c2c1aa6042455ed070f1f6b8b467d73ac363b3967fcdfbe6fd6319b36b0e8d57e23f6a3e7aa6d7f49d4e546c3c8d9ec4d634f06043a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
